codecov:
  require_ci_to_pass: yes
ignore:
  - "**/*.fsx"
  - ".github/"
  - "example/"
  - "test/"
coverage:
  precision: 2
  round: nearest
  range: "80...100"
  status:
    patch:
      default:
        base: auto
        target: auto
        threshold: 5
        if_ci_failed: error
        only_pulls: false
        branches:
          - next
comment:
  layout: "header, condensed_files, condensed_footer"
  require_changes: true
  hide_project_coverage: true
