#!/usr/bin/env bash
for fn in $(git ls-files src/Fornax.Seo/*.fs); do
  dotnet fantomas --check "${fn}" || \
  dotnet fantomas "${fn}" --out "${fn}"
done

for fn in $(git ls-files test/*.fs); do
  dotnet fantomas --check "${fn}" || \
  dotnet fantomas "${fn}" --out "${fn}"
done
