#!/usr/bin/env bash

if [ -z "$GITHUB_REF" ]; then
  echo '********************************************************************'
  echo 'This script must be deployed to GitHub Actions from a tagged commit!'
  echo '********************************************************************'
  exit 2
fi

#
# .NET 6 compatibility remains a work in progress
# https://github.com/fsprojects/FSharp.Formatting/pull/719
#
git checkout -f e8653a7 -- src/Fornax.Seo/Directory.Build.props
sed -i 's/[0-9.]\+/5.0.204/' global.json
sed -i 's/\-f v\$(/-f \$(/'  src/Fornax.Seo/Fornax.Seo.fsproj
dotnet tool install fsdocs-tool --version 14.0.1
dotnet build /v:m /p:nowarn='"3218;3390"' src/Fornax.Seo/Fornax.Seo.fsproj -c Release
cp ./README.md docs/index.md

SITE_ROOT='root https://heredocs.io/Fornax.Seo/' \
dotnet fsdocs build --projects $(pwd)/src/Fornax.Seo/Fornax.Seo.fsproj \
    --eval --clean --strict \
    --properties RepositoryBranch=main Configuration=Release \
    --parameters ${SITE_ROOT} \
        fsdocs-logo-link https://www.nuget.org/packages/Fornax.Seo \
        fsdocs-repository-link https://github.com/rdipardo/Fornax.Seo \
        fsdocs-license-link https://github.com/rdipardo/Fornax.Seo/blob/main/LICENSE \
        fsdocs-release-notes-link https://github.com/rdipardo/Fornax.Seo/blob/main/CHANGELOG.md

rm -f docs/index.md
