name: NuGet
on:
  push:
    tags:
      - '**'
permissions:
  contents: read
jobs:
  package:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: rel-${{ github.ref_name }}
      cancel-in-progress: true
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pre-build Install
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: ./global.json
      - name: Build package
        run: |-
          .\build.cmd -e CI=true Pack
      - name: Collect release info
        run: |
          .\scripts\changelog.ps1 | Out-File release_notes.txt -Encoding utf8
      - name: Save package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Fornax.Seo.${{ github.ref_name }}.nupkg
          path: ${{ github.workspace }}/release/*.nupkg
          retention-days: 30
          if-no-files-found: error
      - name: Prepare release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          body_path: release_notes.txt
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/release/*.nupkg
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
      - name: Obtain NuGet API key
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ github.actor }}
      - name: Publish release
        run: |-
          dotnet nuget push release\Fornax.Seo.${env:RELEASE}.nupkg -k ${env:API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          CI: true
          RELEASE: ${{ github.ref_name }}
          API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
