name: NuGet
on:
  push:
    tags:
      - '**'
permissions:
  contents: read
jobs:
  package:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: rel-${{ github.ref_name }}
      cancel-in-progress: true
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pre-build Install
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: ./global.json
      - name: Build package
        run: |-
          .\build.cmd -e CI=true Pack
      - name: Collect release info
        run: |
          .\scripts\changelog.ps1 | Out-File release_notes.txt -Encoding utf8
      - name: Prepare release
        run: |
          gh release create "$env:tag_name" .\release\*.nupkg --notes-file .\release_notes.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
      - name: Obtain NuGet API key
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ github.actor }}
      - name: Publish release
        run: |-
          dotnet nuget push release\Fornax.Seo.${env:RELEASE}.nupkg -k ${env:API_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          CI: true
          RELEASE: ${{ github.ref_name }}
          API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
